### ISSUE TITLE
Set up Dependabot updates for the client test framework 📦

### ISSUE THREAD

**Issue by hackebrot** [mozilla-services/contile-integration-tests#79]
Currently Dependabot only submits pull requests for Python package upgrades for the `partner`.

Add a new a item to `updates` for the `client` directory in `.github/dependabot.yml`:

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "partner/"
    schedule:
      interval: "daily"
    labels:
      - "Dependabot"
      - "dependencies"
      - "partner"
    open-pull-requests-limit: 10
```
